import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config, findIconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faFacebookF,
  faTwitter,
  faLinkedinIn,
  faInstagram,
  faBehance,
} from "@fortawesome/free-brands-svg-icons";
import { faAnglesDown, faBars } from "@fortawesome/free-solid-svg-icons";
import { useEffect, useState } from "react";
import { Banner } from "@/components/Banner";
import Link from "next/link";
import { Footer } from "@/components/Footer";

config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [navbarOpen, setNavbarOpen] = useState(false);
  const [colorChange, setColorchange] = useState(false);
  useEffect(() => {
    const changeNavbarColor = () => {
      if (window.scrollY >= 80) {
        setColorchange(true);
      } else {
        setColorchange(false);
      }
    };
    window.addEventListener("scroll", changeNavbarColor);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-[#666] text-[15px] leading-[1.8] font-[300] tracking-[0.5px]">
        <nav
          className={`fixed w-full py-[20px] top-0 right-0 left-0 z-[1030] flex flex-wrap items-center justify-between ${
            colorChange ? "bg-[#0C0872]" : "lg:bg-[#00000000]"
          } bg-[#0C0872] transition-all duration-[1s] ease-in-out`}
        >
          <div className="container mx-auto flex flex-wrap items-center justify-between  px-[30px] ">
            <div className="w-full relative flex justify-between lg:w-auto lg:static lg:block lg:justify-start">
              <a
                className="text-[#fff] text-[22px] leading-[50px] h-[50px]  font-bold  inline-block mr-4 py-2 whitespace-nowrap  "
                href="#pablo"
              >
                RoboGard
              </a>
              <button
                className="text-[#fff] cursor-pointer text-xl leading-none px-3 py-1 border border-solid border-transparent rounded bg-transparent block lg:hidden outline-none focus:outline-none"
                type="button"
                onClick={() => setNavbarOpen(!navbarOpen)}
              >
                <FontAwesomeIcon icon={faBars} />
              </button>
            </div>
            <div
              className={
                "lg:flex flex-grow items-center justify-center" +
                (navbarOpen ? " flex" : " hidden")
              }
              id="example-navbar-danger"
            >
              <ul className="flex flex-col lg:flex-row list-none lg:ml-auto">
                <li className="nav-item">
                  <a
                    className="before:opacity-0 before:translate-x-[20px] hover:before:opacity-100 hover:before:translate-x-0 hover:before:translate-y-0 before:mr-[8px] before:content-['['] before:inline-block before:transition-all after:opacity-0 after:translate-x-[-20px]  hover:after:opacity-100 hover:after:translate-x-0 after:translate-y-0 after:ml-[8px] after:content-[']'] after:inline-block after:transition-all duration-[0.3s] ease-in-out before:text-[#00ffff] after:text-[#00ffff]  px-[5px] py-[15px] flex items-center text-[16px] capitalize  font-[500] leading-snug text-[#fff] hover:opacity-75"
                    href="#pablo"
                  >
                    <span className="ml-2">Home</span>
                  </a>
                </li>
                <li className="nav-item">
                  <a
                    className="before:opacity-0 before:translate-x-[20px] hover:before:opacity-100 hover:before:translate-x-0 hover:before:translate-y-0 before:mr-[8px] before:content-['['] before:inline-block before:transition-all after:opacity-0 after:translate-x-[-20px]  hover:after:opacity-100 hover:after:translate-x-0 after:translate-y-0 after:ml-[8px] after:content-[']'] after:inline-block after:transition-all duration-[0.3s] ease-in-out before:text-[#00ffff] after:text-[#00ffff] px-[5px] py-[15px] flex items-center text-[16px] capitalize  font-[500] leading-snug text-[#fff] hover:opacity-75"
                    href="#pablo"
                  >
                    <span className="ml-2">Demos</span>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <Banner
          className={`bg-[url('/images/index-header-bg.svg')]`}
          title="HLS AI Startup & Chabot Template"
          title2="Best AI Template for"
          desc="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut culpa nulla ipsum amet a ab neque. Odio impedit inventore nemo aliquid eius ad? Veniam perferendis iste odio officiis."
          titleColor="text-[#00FFFF]"
          title2Color="text-[#fff]"
          descColor="text-[#fff]"
          buttonClassName="text-[#000] bg-[#fff]"
          animationTextColor="text-[#00FFFF]"
        />

        <section className="pt-[100px] pb-[70px] " id="about">
          <div className="container mx-auto px-[15px]">
            <div className="section_heading pb-[100px] text-center after:absolute after:content-[''] after:blocl after:h-[30px] after:w-[3px] after:left-[50%] after:bg-[#000] after:-translate-x-1/2">
              <h2 className="text-[40px] font-[600] text-[#000] mb-[10px]">
                HLS Demos
              </h2>
              <p className="mb-[20px] max-w-[530px] mx-auto ">
                Our template will be a perfect platform for presenting your AI
                agency. This Landing Page comes in great and clean design
              </p>
            </div>
            <div className="row text-center flex flex-wrap">
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full">
                <Link href="/demo1" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-1.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full">
                <Link href="/demo2" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-2.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full">
                <Link href="/demo3" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-3.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full mt-[32px]">
                <Link href="/demo4" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-4.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full mt-[32px]">
                <Link href="/demo5" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-5.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full mt-[32px]">
                <Link href="/demo6" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-6.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
            </div>
          </div>
        </section>
        <Footer
          className="bg-[url('/images/index-footer-bg.svg')]"
          linkClassName="after:bg-[#fff] text-[#fff]"
          socialItemClassName="text-[#fff] border-[#fff] hover:text-[#fff] hover:before:bg-[#000]"
          coppyRightClassName= 'text-[#fff]'
        />
      </main>
    </>
  );
}
