import Head from "next/head";
import Image from "next/image";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { useEffect, useState } from "react";
import { Banner } from "@/components/Banner";
import Link from "next/link";
import { Footer } from "@/components/Footer";
import { ScrollButton } from "@/components/ScrollButton";
import { PreLoader } from "@/components/Preloader";
import { HomeNavbar } from "../components/Navbar/HomeNavbar";
import { useScrollspy } from "@/hook/useCrollspy";

config.autoAddCss = false;

export default function Home() {
  const ids = ["home", "demo"];
  const activeId = useScrollspy(ids, 91.95);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    const timerId = setTimeout(() => {
      setLoading(false);
    }, 1000);
    return () => clearTimeout(timerId);
  }, []);
  if (loading) {
    return <PreLoader loading={loading} />;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-[#666] text-[15px] leading-[1.8] font-[300] tracking-[0.5px]">
        <HomeNavbar activeId={activeId} />
        <Banner
          className={`bg-[url('/images/index-header-bg.svg')]`}
          title="HLS AI Startup & Chabot Template"
          title2="Best AI Template for"
          desc="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut culpa nulla ipsum amet a ab neque. Odio impedit inventore nemo aliquid eius ad? Veniam perferendis iste odio officiis."
          titleColor="text-[#00FFFF]"
          title2Color="text-[#fff]"
          descColor="text-[#fff]"
          buttonClassName="text-[#000] bg-[#fff]"
          animationTextColor="text-[#00FFFF]"
        />
        <section className="pt-[100px] pb-[70px] " id="demo">
          <div className="container mx-auto px-[15px]">
            <div className="section_heading pb-[100px] text-center after:absolute after:content-[''] after:blocl after:h-[30px] after:w-[3px] after:left-[50%] after:bg-[#000] after:-translate-x-1/2">
              <h2 className="text-[40px] font-[600] text-[#000] mb-[10px]">
                HLS Demos
              </h2>
              <p className="mb-[20px] max-w-[530px] mx-auto ">
                Our template will be a perfect platform for presenting your AI
                agency. This Landing Page comes in great and clean design
              </p>
            </div>
            <div className="row text-center flex flex-wrap">
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full">
                <Link href="/demo1" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-1.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full">
                <Link href="/demo2" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-2.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full">
                <Link href="/demo3" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-3.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full mt-[32px]">
                <Link href="/demo4" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-4.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full mt-[32px]">
                <Link href="/demo5" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-5.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
              <div className="lg:w-1/3 pr-4 pl-4 md:w-1/2 w-full mt-[32px]">
                <Link href="/demo6" target="_blank" className="w-full">
                  <div className="demo-item w-full hover:shadow-[0_-1px_30px_rgba(0,0,0,0.1)]">
                    <div className="demo-img relative w-full h-[597px]">
                      <Image fill src="/images/demos/index-6.svg" alt="s" />
                    </div>
                  </div>
                </Link>
              </div>
            </div>
          </div>
        </section>
        <Footer
          className="bg-[url('/images/index-footer-bg.svg')]"
          linkClassName="after:bg-[#fff] text-[#fff] hover:text-[#dbe3e3]"
          socialItemClassName="text-[#fff] border-[#fff] hover:text-[#fff] hover:before:bg-[#000]"
          coppyRightClassName="text-[#fff]"
        />
        <ScrollButton />
      </main>
    </>
  );
}
